#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/b92d7c8c-0b0b-44da-b50c-b5c819ae0999/ # 
version: v2.0
title: American Flights API
securitySchemes:
  oauth_2_0:
        description: |
            Mule OAuth 2.0.
        type: OAuth 2.0
        describedBy:
            headers:
                Authorization:
                    description: |
                      Used to send a valid OAuth 2 access token. Do not use
                      with the "access_token" query string parameter.
                    type: string
            responses:
                401:
                    description: |
                        Bad or expired token.
                403:
                    description: |
                        Bad OAuth request.
        settings:
          authorizationUri: http://0.0.0.0:8081/authorize
          accessTokenUri: http://0.0.0.0:8081/access-token
          authorizationGrants: [authorization_code, password, client_credentials, implicit]
        
traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string

types: 
  AmericanFlight: !include examples/AmericanFlightDataType.raml

/flights:
  get:
    securedBy: [oauth_2_0]
        
    queryParameters: 
      destination:
        required: false
        enum: 
          - SFO
          - LAX
          - CLE
    responses: 
      200:
        body: 
          application/json:
            type: AmericanFlight[]
            examples: 
              output: !include examples/AmericanFlightsExample.raml 
            
  post:
    body: 
      application/json:
        type: AmericanFlight
        examples: 
          input: !include examples/AmericanFlightNoIDExample.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: Flight added (but not really)
  
  /{ID}:
    
    get:
      responses: 
        200:
          body: 
            application/json:
              type: AmericanFlight
              examples:
                output: !include examples/AmericanFlightExample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Flight deleted (but not really)
    put:
      body:
        application/json:
          type: AmericanFlight
          examples: 
            input: !include examples/AmericanFlightNoIDExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Flight updated (but not really)